name: Config Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  config_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@master
    - name: Setup example config
      run: |
        mv secrets.example.yaml secrets.yaml
        touch cert.pem
        touch key.pem
    - name: Installing HACS (from indomus.it) # www.indomus.it/guide/installare-hacs-home-assistant-community-store-sul-proprio-hub/
      run: |
        echo From www.indomus.it/guide/installare-hacs-home-assistant-community-store-sul-proprio-hub/:
        mkdir custom_components
        cd custom_components/
        git clone https://github.com/custom-components/hacs.git hacs_temp
        cd hacs_temp
        git checkout $(git describe --tags --always $(git rev-list --tags --max-count=1000) | grep -e "[0-9]\+\.[0-9]\+\.[0-9]\+$" | head -n 1)
        cd ../
        cp -r hacs_temp/custom_components/hacs hacs
        rm -R hacs_temp
    - name: HA Config Check
      uses: kpucynski/action-ha-config-check@master
      with:
        ha_version: "latest"
      env:
        HASS_EXTRA_ARGS: "-f -s -i"

  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2

  #  - name: yaml-lint
  #    uses: ibiqlik/action-yamllint@v1
